export default {
  // Navigation
  dashboard: 'Dashboard',
  newReport: 'New Report',
  reports: 'Reports',
  support: 'Support',
  profile: 'Profile',
  logout: 'Logout',
  shipments: 'Shipments',
  customers: 'Customers',
  
  // Dashboard
  welcomeBack: 'Welcome back',
  reportsThisMonth: 'Reports This Month',
  reportsUsed: 'Reports Used',
  reportsRemaining: 'Reports Remaining',
  recentReports: 'Recent Reports',
  viewAll: 'View All',
  createNewReport: 'Create New Report',
  upgradeNow: 'Upgrade Now',
  
  // Report Creation
  describeProduct: 'Describe your product',
  uploadFiles: 'Upload Files',
  productName: 'Product Name',
  countryOfManufacture: 'Country of Manufacture',
  countryOfOrigin: 'Country of Origin',
  destinationCountry: 'Destination Country',
  generateReport: 'Generate Report',
  generating: 'Generating report...',
  
  // Report Details
  reportDetails: 'Report Details',
  hsCode: 'HS Code',
  confidenceScore: 'Confidence Score',
  classificationReasoning: 'Classification Reasoning',
  productCharacteristics: 'Product Characteristics',
  tariffRate: 'Tariff Rate',
  importRequirements: 'Import Requirements',
  officialSources: 'Official Sources',
  alternativeClassifications: 'Alternative Classifications',
  tradeDetails: 'Trade Details',
  
  // New Report Details Keys
  primaryClassification: 'Primary Classification',
  alternativesComparison: 'Alternatives Comparison',
  technicalLegalDetails: 'Technical & Legal Details',
  technicalSpec: 'Technical Spec',
  fullLegalReasoning: 'Full Legal Reasoning',
  complianceRegulation: 'Compliance & Regulation',
  verifiedSources: 'Verified Sources',
  taxesDuties: 'Taxes & Duties',
  standardsCertification: 'Standards & Certification',
  importLegality: 'Import Legality',
  standardizedName: 'Standardized Name',
  materialComposition: 'Material Composition',
  function: 'Function',
  essentialCharacter: 'Essential Character',
  regulatoryContext: 'Regulatory Context',
  regionalAgreements: 'Regional Agreements',
  hsStructure: 'HS Structure',
  taxMethod: 'Tax Method',
  generatedBy: 'Generated by ACE System',
  shareReport: 'Share Report',
  shareReportDesc: 'Copy the public link to this report.',
  linkValidUntil: 'Link valid until: ',
  days: 'days',
  print: 'Print',
  share: 'Share',
  backToReports: 'Back to Reports',
  qaScore: 'Holistic Quality Score',
  attentionNeeded: 'Attention Needed',
  qaPassed: 'This report has passed quality assurance checks. This classification is considered reliable.',
  whyRejected: 'Why rejected',
  officialResourceLinks: 'Official Resource Links',
  noSpecificStandards: 'No specific standards found.',
  noneSpecified: 'None specified',
  verifySource: 'Verify Source',
  origin: 'Origin',
  destination: 'Destination',

  // Public Report
  publicReport: 'Shared Report',
  sharedVia: 'This report was shared via Tariff AI',
  securityLevel: 'Confidence Level',
  invalidLink: 'Invalid Link',
  linkExpired: 'Link expired or invalid',
  tariffInformation: 'Tariff Information',

  // Support
  contactSupport: 'Contact Support',
  subject: 'Subject',
  category: 'Category',
  message: 'Message',
  submit: 'Submit',
  billing: 'Billing',
  technical: 'Technical',
  classification: 'Classification',
  account: 'Account',
  other: 'Other',
  
  // Profile
  personalInfo: 'Personal Information',
  companyName: 'Company Name',
  email: 'Email',
  phone: 'Phone',
  subscription: 'Subscription',
  currentPlan: 'Current Plan',
  preferences: 'Preferences',
  language: 'Language',
  systemLanguage: 'System Language',
  defaultReportLanguage: 'Default Report Language',
  theme: 'Theme',
  light: 'Light',
  dark: 'Dark',
  save: 'Save',
  
  // Plans - Old flat keys kept for backward compat or if used elsewhere, but new structure is below
  free: 'Free',
  payPerUse: 'Pay Per Use',
  basic: 'Basic',
  pro: 'Pro',
  agency: 'Agency',
  enterprise: 'Enterprise',
  reportsPerMonth: 'reports/month',
  perReport: '/report',
  perMonth: '/month',
  contactUs: 'Contact Us',

  // Pricing Object
  pricing: {
    free: {
      title: 'Free',
      features: ['Up to 3 reports/month', 'Limited report view', 'HS Code only']
    },
    payPerUse: {
      title: 'Pay Per Use',
      features: ['$1.99 per report', 'Full report view', 'Unlimited']
    },
    basic: {
      title: 'Basic',
      features: ['Up to 15 reports/month', 'Full report view', 'Email support']
    },
    pro: {
      title: 'Pro',
      features: ['Up to 50 reports/month', 'Full report view', 'Priority support', 'PDF export']
    },
    agency: {
      title: 'Agency',
      features: ['Up to 200 reports/month', 'Full report view', 'Premium support', 'API access']
    },
    enterprise: {
      title: 'Enterprise',
      features: ['Unlimited reports', 'Custom solutions', 'Dedicated account manager', 'Custom SLA']
    }
  },
  
  // Status
  processing: 'Processing',
  completed: 'Completed',
  failed: 'Failed',
  open: 'Open',
  inProgress: 'In Progress',
  resolved: 'Resolved',
  closed: 'Closed',
  
  // Common
  loading: 'Loading...',
  error: 'Error',
  success: 'Success',
  cancel: 'Cancel',
  delete: 'Delete',
  edit: 'Edit',
  view: 'View',
  download: 'Download',
  search: 'Search',
  noResults: 'No results',
  close: 'Close',
  copy: 'Copy',
  
  // Disclaimer
  disclaimer: 'This report was generated by AI and does not constitute official legal or customs advice. Please verify the information with official customs authorities.',
  
  // Clarify Page & Notifications
  waiting_for_user: 'Waiting for User',
  action_required: 'Action Required',
  missingInformation: 'Missing Information',
  caseContext: 'Case Context',
  expertRequest: 'Expert Request',
  provideInfo: 'Provide Info',
  originalInput: 'Original Input',
  forceProceed: 'Force Proceed (Risk Low Accuracy)',
  submitUpdate: 'Submit Update',
  back: 'Back',
  classificationReady: 'Classification Ready',
  processFailed: 'Process Failed',
  resolveNow: 'Resolve Now',
  viewReport: 'View Report',
  product: 'PRODUCT',
  reportId: 'Report ID',
  file: 'File',
  link: 'Link',
  notifications: 'Notifications',
  markAllAsRead: 'Mark all as read',
  noNotifications: 'No notifications',
  viewNotification: 'View',
  notificationDismissed: 'Notification dismissed'
};